'use client';
import { motion } from 'motion/react';
import { AlertTriangle, ArrowRight } from 'lucide-react';
import { cn, sr } from './sampleReportTailwind';
const ease = [0.22, 1, 0.36, 1] as const;
const blockers = [
  { title: 'Financial model is not investor-ready', desc: 'The assumptions are not clear enough to support the funding ask.', priority: 'High Priority', fix: 'Clarify assumptions, runway logic, revenue scenarios, and how the raise supports milestones.', high: true },
  { title: 'Use of funds is too general', desc: 'The report needs to show exactly how the capital will be used and why that amount makes sense.', priority: 'High Priority', fix: 'Break the raise into hiring, product, marketing, operations, and runway categories.', high: true },
  { title: 'Pitch narrative lacks urgency', desc: 'The deck explains the product but does not clearly explain why now, why this team, and why this market.', priority: 'Medium Priority', fix: 'Sharpen the story around timing, traction, founder credibility, and market pull.', high: false },
  { title: 'Data room is incomplete', desc: 'Important documents are missing or not organized for review.', priority: 'Medium Priority', fix: 'Prepare a basic data room checklist and organize missing company documents.', high: false },
];
export function SRBlockers() { return <section className={sr.sectionCream}><div className={sr.containerMd}><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,ease}} className={sr.header}><span className={sr.eyebrow}>Priority blockers</span><h2 className={sr.title}>Top funding blockers detected.</h2><p className={sr.description}>These are the issues most likely to create confusion, hesitation, or rejection during funding review.</p></motion.div><div className="grid grid-cols-1 gap-5 md:grid-cols-2">{blockers.map((blocker,i)=><motion.div key={blocker.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.5,delay:i*.09,ease}} className={cn('rounded-3xl border bg-white p-7 transition-shadow', blocker.high?'border-[var(--color-brand-orange)] shadow-[0_8px_28px_rgba(253,102,40,0.08)]':'border-[var(--color-border)] shadow-[0_4px_20px_rgba(0,0,0,0.04)]')}><div className="mb-3 flex items-start justify-between gap-3"><div className="flex flex-1 items-start gap-3"><div className={cn('flex size-9 shrink-0 items-center justify-center rounded-[10px]', blocker.high?'bg-[var(--color-brand-orange-tint)] text-[var(--color-brand-orange)]':'bg-[rgba(0,0,0,0.05)] text-[var(--color-text-subtle)]')}><AlertTriangle size={17}/></div><div className="flex-1 font-[Manrope,sans-serif] text-[15px] font-bold leading-[1.3] text-[var(--color-text-primary)]">{blocker.title}</div></div><span className={cn('shrink-0 whitespace-nowrap rounded-[var(--radius-pill)] px-2.5 py-1 text-[10px] font-bold', blocker.high?'bg-[var(--color-brand-orange)] text-white':'bg-[rgba(0,0,0,0.06)] text-[var(--color-text-muted)]')}>{blocker.priority}</span></div><p className="mb-4 text-[13px] leading-[1.65] text-[var(--color-text-tertiary)]">{blocker.desc}</p><div className="border-t border-[var(--color-border-divider)] pt-3.5"><div className="mb-1.5 text-[11px] font-bold uppercase tracking-[0.05em] text-[var(--color-text-faint)]">Suggested fix</div><div className="flex items-start gap-2"><ArrowRight size={13} className="mt-0.5 shrink-0 text-[var(--color-brand-orange)]"/><p className="m-0 text-[13px] leading-[1.55] text-[var(--color-text-secondary)]">{blocker.fix}</p></div></div></motion.div>)}</div></div></section> }
