'use client';
import { motion, useInView } from 'motion/react';
import { useRef } from 'react';
import { cn, sr } from './sampleReportTailwind';
const ease = [0.22, 1, 0.36, 1] as const;
const categories = [
  { name: 'Pitch Narrative', score: 58, insight: 'Needs clearer story', status: 'Needs Work', priority: false }, { name: 'Pitch Deck Structure', score: 64, insight: 'Some structure, needs sharper flow', status: 'Watch Area', priority: false }, { name: 'Financial Readiness', score: 45, insight: 'Main weakness', status: 'Priority Gap', priority: true }, { name: 'Traction Clarity', score: 72, insight: 'Good early signal', status: 'Strong', priority: false }, { name: 'Data Room Readiness', score: 38, insight: 'Missing documents', status: 'Missing', priority: true }, { name: 'Use of Funds', score: 52, insight: 'Needs stronger logic', status: 'Needs Work', priority: false }, { name: 'Market Positioning', score: 68, insight: 'Promising but needs focus', status: 'Watch Area', priority: false }, { name: 'Capital Pathway Fit', score: 61, insight: 'Needs clearer direction', status: 'Needs Work', priority: false },
];
const statusClass: Record<string,string>={ 'Needs Work':'bg-[var(--color-brand-orange-tint)] text-[var(--color-brand-orange)]','Watch Area':'bg-[rgba(0,0,0,0.06)] text-[var(--color-text-tertiary)]','Priority Gap':'bg-[rgba(253,102,40,0.15)] text-[var(--color-brand-orange)]','Strong':'bg-[rgba(34,197,94,0.1)] text-[#16a34a]','Missing':'bg-[rgba(253,102,40,0.15)] text-[var(--color-brand-orange)]'};
function ProgressBar({score,animate:shouldAnimate}:{score:number;animate:boolean}){return <div className="my-2.5 h-1.5 overflow-hidden rounded-[3px] bg-[var(--color-border-divider)]"><motion.div initial={{width:0}} animate={shouldAnimate?{width:`${score}%`}:{}} transition={{duration:.9,ease:[0.22,1,0.36,1]}} className={cn('h-full rounded-[3px]',score<50?'bg-[var(--color-brand-orange)]':score<65?'bg-[#f59e0b]':'bg-[#22c55e]')}/></div>}
export function SRCategoryBreakdown(){const ref=useRef<HTMLDivElement>(null);const isInView=useInView(ref,{once:true,margin:'-60px'});return <section className={sr.sectionCream}><div className={sr.containerLg}><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,ease}} className={sr.header}><span className={sr.eyebrow}>Category breakdown</span><h2 className={sr.title}>Readiness category breakdown.</h2><p className={sr.description}>The overall score is supported by review categories that show where the company is stronger and where preparation is still needed.</p></motion.div><div ref={ref} className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((cat,i)=><motion.div key={cat.name} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.45,delay:i*.07,ease}} className={cn('rounded-[22px] border bg-white p-[22px]',cat.priority?'border-[var(--color-brand-orange)] shadow-[0_4px_20px_rgba(253,102,40,0.08)]':'border-[var(--color-border)] shadow-[0_4px_16px_rgba(0,0,0,0.04)]')}><div className="mb-1.5 flex items-start justify-between gap-2"><div className="flex-1 font-[Manrope,sans-serif] text-sm font-bold leading-[1.3] text-[var(--color-text-primary)]">{cat.name}</div><div className="shrink-0 font-[Manrope,sans-serif] text-lg font-extrabold text-[var(--color-text-primary)]">{cat.score}</div></div><ProgressBar score={cat.score} animate={isInView}/><div className="flex items-center justify-between gap-2"><p className="m-0 flex-1 text-xs leading-[1.4] text-[var(--color-text-subtle)]">{cat.insight}</p><span className={cn('shrink-0 whitespace-nowrap rounded-[var(--radius-pill)] px-2 py-[3px] text-[10px] font-bold',statusClass[cat.status])}>{cat.status}</span></div></motion.div>)}</div></div></section>}
