'use client';
import { motion } from 'motion/react';
import { Check, AlertTriangle, Minus } from 'lucide-react';
import { cn, sr } from './sampleReportTailwind';
const ease=[0.22,1,0.36,1] as const;
const docs=[{name:'Company Overview',status:'Ready',note:'Investors need a clear one-pager to start review.',priority:'Low'},{name:'Pitch Deck',status:'Needs Work',note:'Key slides are unclear or missing key information.',priority:'High'},{name:'Financial Model',status:'Needs Work',note:'Assumptions and runway logic need clarification.',priority:'High'},{name:'Cap Table',status:'Missing',note:'Equity structure must be clear before serious review.',priority:'High'},{name:'Incorporation Documents',status:'Missing',note:'Legal entity documents are required for due diligence.',priority:'Medium'},{name:'Customer / Traction Proof',status:'Partial',note:'Early data exists but needs stronger presentation.',priority:'Medium'},{name:'Use-of-Funds Breakdown',status:'Missing',note:'How capital will be used must be clearly explained.',priority:'High'},{name:'Product Demo or Screenshots',status:'Ready',note:'Product is visible and easy to understand.',priority:'Low'}];
function StatusPill({status}:{status:string}){const cls=status==='Ready'?'bg-[rgba(34,197,94,0.1)] text-[#16a34a]':status==='Partial'?'bg-[rgba(0,0,0,0.06)] text-[var(--color-text-muted)]':status==='Missing'?'bg-[rgba(253,102,40,0.15)] text-[var(--color-brand-orange)]':'bg-[var(--color-brand-orange-tint)] text-[var(--color-brand-orange)]';const Icon=status==='Ready'?Check:status==='Partial'?Minus:AlertTriangle;return <span className={cn('inline-flex items-center gap-1 rounded-[var(--radius-pill)] px-2.5 py-1 text-[11px] font-bold',cls)}><Icon size={12}/>{status}</span>}
const pri:Record<string,string>={High:'text-[var(--color-brand-orange)]',Medium:'text-[var(--color-text-subtle)]',Low:'text-[#BBBBBB]'};
export function SRDataRoom(){return <section className={sr.sectionWhite}><div className={sr.containerMd}><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,ease}} className={sr.header}><span className={sr.eyebrow}>Document readiness</span><h2 className={sr.title}>Data room checklist preview.</h2><p className={sr.description}>The report shows which documents are ready, missing, or need improvement before serious review.</p></motion.div><motion.div initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,ease}} className="hidden overflow-hidden rounded-3xl border border-[var(--color-border)] bg-white shadow-[0_8px_30px_rgba(0,0,0,0.05)] md:block"><div className="grid grid-cols-[2fr_1fr_2fr_1fr] border-b-2 border-[var(--color-border-divider)] bg-[#F8F8F8]">{['Document','Status','Why it matters','Priority'].map((h,i)=><div key={h} className={cn('px-5 py-3.5 text-[11px] font-bold uppercase tracking-[0.05em] text-[var(--color-text-subtle)]',i>0&&'border-l border-[var(--color-border-divider)]')}>{h}</div>)}</div>{docs.map((doc,i)=><motion.div key={doc.name} initial={{opacity:0,y:6}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.3,delay:i*.05,ease}} className={cn('grid grid-cols-[2fr_1fr_2fr_1fr]',i<docs.length-1&&'border-b border-[#F8F8F8]')}><div className="px-5 py-4 text-sm font-semibold text-[var(--color-text-primary)]">{doc.name}</div><div className="border-l border-[#F8F8F8] px-5 py-4"><StatusPill status={doc.status}/></div><div className="border-l border-[#F8F8F8] px-5 py-4 text-[13px] leading-normal text-[var(--color-text-muted)]">{doc.note}</div><div className={cn('border-l border-[#F8F8F8] px-5 py-4 text-xs font-bold',pri[doc.priority])}>{doc.priority}</div></motion.div>)}</motion.div><div className="flex flex-col gap-3 md:hidden">{docs.map((doc,i)=><motion.div key={doc.name} initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.35,delay:i*.05,ease}} className="rounded-[18px] border border-[var(--color-border)] bg-white px-5 py-[18px]"><div className="mb-2 flex items-start justify-between gap-2.5"><div className="text-sm font-bold text-[var(--color-text-primary)]">{doc.name}</div><StatusPill status={doc.status}/></div><p className="mb-2 text-[13px] leading-normal text-[var(--color-text-muted)]">{doc.note}</p><span className={cn('text-[11px] font-bold',pri[doc.priority])}>Priority: {doc.priority}</span></motion.div>)}</div></div></section>}
