'use client';
import { motion, useMotionValue, useSpring, animate, useInView } from 'motion/react';
import { useEffect, useRef } from 'react';
import { cn, sr } from './sampleReportTailwind';
const ease=[0.22,1,0.36,1] as const;
const bands=[{range:'0–39',label:'Not Ready',active:false},{range:'40–59',label:'Major Gaps',active:false},{range:'60–74',label:'Preparation Needed',active:true},{range:'75–89',label:'Near Ready',active:false},{range:'90–100',label:'Strong Readiness',active:false}];
const SCORE=62;
function AnimatedScoreRing(){const ref=useRef<HTMLDivElement>(null);const isInView=useInView(ref,{once:true,margin:'-80px'});const raw=useMotionValue(0);const val=useSpring(raw,{stiffness:50,damping:18});const countRef=useRef<HTMLSpanElement>(null);const size=180;const r=(size-16)/2;const circ=2*Math.PI*r;useEffect(()=>{if(!isInView)return;const ctrl=animate(raw,SCORE,{duration:1.6,ease:'easeOut',delay:.2});const unsub=val.on('change',v=>{if(countRef.current)countRef.current.textContent=Math.round(v).toString();});return()=>{ctrl.stop();unsub();};},[isInView,raw,val]);return <div ref={ref} className="relative size-[180px]"><svg width={size} height={size} className="-rotate-90"><circle cx={size/2} cy={size/2} r={r} fill="none" stroke="var(--color-border-divider)" strokeWidth={14}/><motion.circle cx={size/2} cy={size/2} r={r} fill="none" stroke="var(--color-brand-orange)" strokeWidth={14} strokeLinecap="round" strokeDasharray={circ} initial={{strokeDashoffset:circ}} animate={isInView?{strokeDashoffset:circ-(circ*SCORE)/100}:{}} transition={{duration:1.6,delay:.2,ease:[0.22,1,0.36,1]}}/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span ref={countRef} className="font-[Manrope,sans-serif] text-[52px] font-extrabold leading-none text-[var(--color-text-primary)]">0</span><span className="text-sm font-medium text-[var(--color-text-subtle)]">/ 100</span></div></div>}
export function SRScore(){return <section className={sr.sectionWhite}><div className={sr.containerMd}><motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,ease}} className={sr.header}><span className={sr.eyebrow}>Diagnostic score</span><h2 className={sr.title}>Overall funding readiness score.</h2><p className={sr.description}>The readiness score gives founders a starting point. It helps show whether the company appears prepared for serious funding review or needs more work before outreach.</p></motion.div><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.6,ease}} className="rounded-[28px] border border-[var(--color-border)] bg-white p-[clamp(28px,4vw,48px)] shadow-[0_20px_60px_rgba(0,0,0,0.05)]"><div className="grid grid-cols-1 items-center gap-10 md:grid-cols-2"><div className="flex flex-col items-center gap-5"><AnimatedScoreRing/><div className="text-center"><div className="mb-2.5 inline-block rounded-[var(--radius-pill)] bg-[var(--color-brand-orange-tint-soft)] px-4 py-1.5 text-[13px] font-bold text-[var(--color-brand-orange)]">Preparation Needed Before Outreach</div><p className="m-0 max-w-[340px] text-sm leading-[1.65] text-[var(--color-text-tertiary)]">The company has early traction and a clear market opportunity, but the funding narrative, financial model, and use-of-funds logic need improvement before serious capital conversations.</p></div></div><div className="flex flex-col gap-2.5"><div className="mb-2 text-xs font-bold uppercase tracking-[0.06em] text-[var(--color-text-subtle)]">Score bands</div>{bands.map((band,i)=><motion.div key={band.range} initial={{opacity:0,x:12}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.4,delay:i*.07,ease}} className={cn('flex items-center gap-3.5 rounded-[14px] border px-[18px] py-3.5',band.active?'border-[var(--color-brand-orange)] bg-[rgba(253,102,40,0.06)]':'border-transparent bg-[#F8F8F8]')}><div className={cn('w-9 shrink-0 font-[Manrope,sans-serif] text-xs font-bold',band.active?'text-[var(--color-brand-orange)]':'text-[var(--color-text-faint)]')}>{band.range}</div><div className={cn('h-6 w-0.5 shrink-0',band.active?'bg-[var(--color-brand-orange)]':'bg-[var(--color-border)]')}/><div className={cn('font-[Manrope,sans-serif] text-sm',band.active?'font-bold text-[var(--color-text-primary)]':'font-medium text-[var(--color-text-muted)]')}>{band.label}</div>{band.active&&<div className="ml-auto rounded-[var(--radius-pill)] bg-[var(--color-brand-orange-tint)] px-2.5 py-[3px] text-[11px] font-bold text-[var(--color-brand-orange)]">Current</div>}</motion.div>)}<p className="mt-2 text-xs leading-normal text-[var(--color-text-faint)]">The score is a starting point for diagnosis, not a final verdict. The real value is in the detailed review.</p></div></div></motion.div></div></section>}
