export const legalTw = {
  page: 'font-[var(--font-body)] bg-[var(--color-bg-cream)]',
  heroSection: 'bg-[var(--color-bg-cream)] pt-[120px] pb-14',
  heroContainer: 'mx-auto max-w-[var(--container-narrow)] px-6 text-center',
  eyebrow: 'mb-5 inline-block rounded-[var(--radius-pill)] bg-[var(--color-brand-orange-tint)] px-[14px] py-[5px] text-[12px] font-bold uppercase tracking-[var(--letter-spacing-wider)] text-[var(--color-brand-orange)]',
  heroTitle: 'mb-[18px] text-[clamp(30px,4.5vw,50px)] font-extrabold leading-[var(--line-height-tight)] tracking-[var(--letter-spacing-tight)] text-[var(--color-text-primary)]',
  heroCopy: 'mb-4 text-[17px] leading-[var(--line-height-relaxed)] text-[var(--color-text-secondary)]',
  lastUpdated: 'text-[13px] font-medium text-[var(--color-text-subtle)]',
  container: 'mx-auto max-w-[var(--container-narrow)] px-6 pb-20',
  panel: 'mb-6 overflow-hidden rounded-[var(--radius-card-lg)] border-[1.5px] border-[var(--color-border)] bg-[var(--color-bg-white)]',
  tocButton: 'flex w-full cursor-pointer items-center justify-between bg-transparent px-7 py-[18px] font-[var(--font-body)]',
  tocButtonOpen: 'border-b-[1.5px] border-[var(--color-border)]',
  tocTitle: 'text-[14px] font-bold text-[var(--color-text-primary)]',
  tocIcon: 'text-[var(--color-text-secondary)]',
  tocList: 'flex flex-col gap-1 px-7 py-5',
  tocItem: 'flex cursor-pointer items-center gap-2.5 rounded-lg bg-transparent px-2 py-1.5 text-left font-[var(--font-body)] transition-all duration-150 hover:bg-[rgba(253,102,40,0.07)] hover:text-[var(--color-brand-orange)]',
  tocNumber: 'min-w-5 text-[12px] font-bold text-[var(--color-brand-orange)]',
  tocLabel: 'text-[14px] font-medium text-[var(--color-text-secondary)] group-hover:text-[var(--color-brand-orange)]',
  notice: 'mb-6 flex items-start gap-3.5 rounded-[var(--radius-card)] border-[1.5px] border-l-4 border-[var(--color-border)] border-l-[var(--color-brand-orange)] bg-[var(--color-bg-white)] px-6 py-5',
  noticeIcon: 'mt-0.5 shrink-0 text-[var(--color-brand-orange)]',
  noticeTitle: 'mb-1 text-[13px] font-bold text-[var(--color-text-primary)]',
  noticeText: 'm-0 text-[14px] leading-[var(--line-height-relaxed)] text-[var(--color-text-secondary)]',
  topCards: 'mb-6',
  contentCard: 'mb-8 rounded-[var(--radius-card-2xl)] border-[1.5px] border-[var(--color-border)] bg-[var(--color-bg-white)] py-14 px-6 md:px-16',
  cta: 'rounded-[var(--radius-card-xl)] border-[1.5px] border-[var(--color-border)] bg-[var(--color-bg-white)] py-10 px-6 text-center md:px-12',
  ctaTitle: 'mb-2.5 text-[22px] font-extrabold tracking-[var(--letter-spacing-snug)] text-[var(--color-text-primary)]',
  ctaText: 'mx-auto mb-7 max-w-[460px] text-[15px] leading-[var(--line-height-relaxed)] text-[var(--color-text-secondary)]',
  ctaActions: 'flex flex-wrap justify-center gap-3',
  primaryLink: 'inline-flex items-center gap-2 rounded-[var(--radius-pill)] bg-[var(--color-bg-black)] px-[22px] py-3 text-[14px] font-bold text-[var(--color-text-on-dark)] no-underline transition-all duration-200 hover:bg-[#222]',
  secondaryLink: 'inline-flex items-center gap-2 rounded-[var(--radius-pill)] border-[1.5px] border-[var(--color-border)] bg-[var(--color-bg-white)] px-[22px] py-3 text-[14px] font-bold text-[var(--color-text-primary)] no-underline transition-all duration-200 hover:border-[var(--color-text-primary)]',
  contactWrap: 'mt-5',
  contactLink: 'text-[13px] font-semibold text-[var(--color-brand-orange)] no-underline hover:underline',
};
